from pathlib import Path

TEST_DATA_DIR = Path("tests/test_data")
GFAP_DATA_DIR = TEST_DATA_DIR / "GFAP_P14136"
GFAP_EXTENDED_DATA_DIR = TEST_DATA_DIR / "GFAP_P14136_extended"
TAU_DATA_DIR = TEST_DATA_DIR / "TAU_P10636"
SATB1_DATA_DIR = TEST_DATA_DIR / "SATB1_Q01826"
